### ISSUE TITLE
Add me please

### ISSUE THREAD

**Issue by kg6hxm** [doctordns/MastoPosh#6]
I would like to be added to the list.

@kg6hxm@social.makerforums.info

Thanks!

**Comment by doctordns** [comment]
Sure - can you let me have your Name, and settings for ShowBoosts, NotifynewPosts and Language?

**Comment by kg6hxm** [comment]
I'm not sure what ShowBoosts, NotifynewPosts are. I am unfortunately only
fluent in English.

Sam Hetchler
970.430.6688

**Comment by doctordns** [comment]
I have added added this to the CSV>

Thanks
